- KNN适用:KNN是一种有监督学习算法，适用于分类和回归问题.
    - 分类: 找最近的K个邻居(距离最近的K个点)，根据它们的类别进行投票，确定新数据点的类别.
    - 回归: 找最近的K个邻居，计算它们的平均值，作为新数据点的预测值.

- 欧式距离: 计算两点之间的直线距离，适用于连续数值特征.
    - 公式: d(p, q) = sqrt((p1 - q1)^2 + (p2 - q2)^2 + ... + (pn - qn)^2)

- K 太小: 模型可能过拟合，容易受到噪声数据的影响.(投票人少，容易被异常特征值影响)
- K 太大: 模型可能欠拟合，无法捕捉数据的局部结构.(投票人多，模型太简单)
- K值可以超参优化,交叉验证,网格搜索

- 分类流程:
    1. 计算每个样本到训练样本的距离.
    2. 距离升序排列
    3. 选择距离最近的K个邻居.
    4. 根据K个邻居的类别进行投票，确定新数据点的类别.(投票数相同,选择预测值最小的类别)
- 回归流程
    1. 计算每个样本到训练样本的距离.
    2. 距离升序排列
    3. 选择距离最近的K个邻居.
    4. 计算K个邻居的平均值，作为新数据点的预测值.

In [16]:
# KNN 分类->投票
from sklearn.neighbors import KNeighborsClassifier

# 训练数据
x_train = [[0], [1], [2], [3]] 
y_train = [0, 0, 1, 1]

# 创建 KNN 分类器 K=3
knn = KNeighborsClassifier(n_neighbors=3)

# 训练模型
knn.fit(x_train, y_train)

# 测试数据
x_test = [[1.5], [2.5]]
# 预测类别
y_pred = knn.predict(x_test)
print(y_pred)  # 输出: [0 1]

[0 1]


In [17]:
# KNN 回归-> 平均值
from sklearn.neighbors import KNeighborsRegressor

# 训练数据
x_train = [[0, 0, 1], [1, 1, 0], [3, 10, 10], [4, 11, 12]]
y_train = [0.1, 0.2, 0.3, 0.4]

# 创建 KNN 回归器 K=2
knn_reg = KNeighborsRegressor(n_neighbors=2)

# 训练模型
knn_reg.fit(x_train, y_train)

# 测试数据
x_test = [[1, 1, 1], [3, 10, 11]]
# 预测数值
y_pred = knn_reg.predict(x_test)
print(y_pred)  # 输出: [0.15 (0.1+0.2)/2=0.15, 0.35 (0.3+0.4)/2=0.35]

[0.15 0.35]


- 距离计算

    - 欧式距离: 计算两点之间的直线距离
        - 公式: d(p, q) = sqrt((p1 - q1)^2 + (p2 - q2)^2 + ... + (pn - qn)^2)
    - 曼哈顿距离: 计算两点之间的绝对距离(两点城市街区最小距离)
        - 公式: d(p, q) = |p1 - q1| + |p2 - q2| + ... + |pn - qn|

    - 切比雪夫距离: 计算两点之间的最大距离(国际象棋中皇后移动到某个点的最少步数)
        - 公式: d(p, q) = max(|p1 - q1|, |p2 - q2|, ..., |pn - qn|)
    
    - 闵可夫斯基距离: 欧式距离和曼哈顿距离的推广
        - 公式: d(p, q) = (|p1 - q1|^m + |p2 - q2|^m + ... + |pn - qn|^m)^(1/m)
        - m=1: 曼哈顿距离
        - m=2: 欧式距离
        - m=∞: 切比雪夫距离

- 特征标准化
    - 归一化: 将特征缩放到[0, 1]范围内 (受到异常值的影响较大)
        - 公式: x' = (x - min) / (max - min)
        - 如果需要将数据映射到[mi,mx]范围内,公式: x'' = x' * (mx - mi) + mi
    - 标准化: 将特征缩放到均值为0，标准差为1的范围内
        - 公式: x' = (x - mean) / std (不受异常值的影响)
        - std：标准差，衡量数据的离散程度，计算公式: std = sqrt(1/n * Σ(xi - mean)^2)

In [ ]:
# 特征标准化 -> 归一化
from sklearn.preprocessing import MinMaxScaler
import numpy as np

x_train = [[90, 2, 10, 40], [60, 4, 15, 45], [75, 3, 12, 46]]
scaler = MinMaxScaler(feature_range=(0, 1)) # 创建归一化对象，指定特征范围为[0, 1]

# 归一化
x_train_scaled = scaler.fit_transform(x_train)
print(x_train_scaled)

[[1.         0.         0.         0.        ]
 [0.         1.         1.         0.83333333]
 [0.5        0.5        0.4        1.        ]]


In [24]:
# 特征标准化 -> 标准化
from sklearn.preprocessing import StandardScaler

x_train = [[90, 2, 10, 40], [60, 4, 15, 45], [75, 3, 12, 46]]
scaler = StandardScaler() # 创建标准化对象

# 标准化
x_train_scaled = scaler.fit_transform(x_train)
print(x_train_scaled)

print(f"数据列均值: {scaler.mean_}") # 输出数据列均值
print(f"数据列标准差: {scaler.scale_}") # 输出数据列标准差
print(f"数据列方差: {scaler.var_}") # 输出数据列方差

[[ 1.22474487 -1.22474487 -1.13554995 -1.3970014 ]
 [-1.22474487  1.22474487  1.29777137  0.50800051]
 [ 0.          0.         -0.16222142  0.88900089]]
数据列均值: [75.          3.         12.33333333 43.66666667]
数据列标准差: [12.24744871  0.81649658  2.05480467  2.62466929]
数据列方差: [150.           0.66666667   4.22222222   6.88888889]


- 交叉验证: 划分数据集的方法,将数据集划分为CV个子集,每次使用CV-1个子集进行训练,剩下的一个子集进行测试,重复CV次,计算平均性能指标.
    - 适用于评估模型的泛化能力,选择KNN最佳的CV值.
    - 找到最佳的CV组值后,使用这组整个训练数据集重新训练模型,然后在这组测试集上评估性能.

- 网格搜索: 超参数优化方法,通过穷举法搜索指定的超参数空间,找到最佳的超参数组合.
    - 使用交叉验证评估每个超参数组合的性能,选择性能最好的组合作为最终模型的超参数.

- n_neighbors=[1,2,3,5,7]； cv=4 => 20次训练和评估模型,每次使用不同的K值和CV值组合,找到最佳的K值和CV值组合.

- 上面两种通常作为模型优化调参方法

In [ ]:
'''
from sklearn.model_selection import GridSearchCV

GridSearchCV(
    estimator=KNeighborsClassifier(), # 需要优化的模型
    param_grid={'n_neighbors': [1, 2, 3, 5, 7]}, # 超参数空间
    cv=4, # 交叉验证折数
    scoring='accuracy' # 性能评估指标
)
"""
结果: 
    - bestscore_: 交叉验证中最佳性能指标得分
    - bestestimator: 交叉验证中最佳模型
    - cvresults: 交叉验证中每个超参数组合的性能指标得分
"""
'''

NameError: name 'KNeighborsClassifier' is not defined